// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/appointment.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAppointmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PatientId     string                 `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,2,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Date          string                 `protobuf:"bytes,3,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAppointmentRequest) Reset() {
	*x = CreateAppointmentRequest{}
	mi := &file_proto_appointment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAppointmentRequest) ProtoMessage() {}

func (x *CreateAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAppointmentRequest.ProtoReflect.Descriptor instead.
func (*CreateAppointmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAppointmentRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *CreateAppointmentRequest) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

type AppointmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PatientId     string                 `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	DoctorId      string                 `protobuf:"bytes,3,opt,name=doctor_id,json=doctorId,proto3" json:"doctor_id,omitempty"`
	Date          string                 `protobuf:"bytes,4,opt,name=date,proto3" json:"date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppointmentResponse) Reset() {
	*x = AppointmentResponse{}
	mi := &file_proto_appointment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppointmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppointmentResponse) ProtoMessage() {}

func (x *AppointmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_appointment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppointmentResponse.ProtoReflect.Descriptor instead.
func (*AppointmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_appointment_proto_rawDescGZIP(), []int{1}
}

func (x *AppointmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AppointmentResponse) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *AppointmentResponse) GetDoctorId() string {
	if x != nil {
		return x.DoctorId
	}
	return ""
}

func (x *AppointmentResponse) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

var File_proto_appointment_proto protoreflect.FileDescriptor

const file_proto_appointment_proto_rawDesc = "" +
	"\n" +
	"\x17proto/appointment.proto\x12\vappointment\"j\n" +
	"\x18CreateAppointmentRequest\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x01 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x02 \x01(\tR\bdoctorId\x12\x12\n" +
	"\x04date\x18\x03 \x01(\tR\x04date\"u\n" +
	"\x13AppointmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"patient_id\x18\x02 \x01(\tR\tpatientId\x12\x1b\n" +
	"\tdoctor_id\x18\x03 \x01(\tR\bdoctorId\x12\x12\n" +
	"\x04date\x18\x04 \x01(\tR\x04date2r\n" +
	"\x12AppointmentService\x12\\\n" +
	"\x11CreateAppointment\x12%.appointment.CreateAppointmentRequest\x1a .appointment.AppointmentResponseB+Z)github.com/ddukssu/gogo/appointment/protob\x06proto3"

var (
	file_proto_appointment_proto_rawDescOnce sync.Once
	file_proto_appointment_proto_rawDescData []byte
)

func file_proto_appointment_proto_rawDescGZIP() []byte {
	file_proto_appointment_proto_rawDescOnce.Do(func() {
		file_proto_appointment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_appointment_proto_rawDesc), len(file_proto_appointment_proto_rawDesc)))
	})
	return file_proto_appointment_proto_rawDescData
}

var file_proto_appointment_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_appointment_proto_goTypes = []any{
	(*CreateAppointmentRequest)(nil), // 0: appointment.CreateAppointmentRequest
	(*AppointmentResponse)(nil),      // 1: appointment.AppointmentResponse
}
var file_proto_appointment_proto_depIdxs = []int32{
	0, // 0: appointment.AppointmentService.CreateAppointment:input_type -> appointment.CreateAppointmentRequest
	1, // 1: appointment.AppointmentService.CreateAppointment:output_type -> appointment.AppointmentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_appointment_proto_init() }
func file_proto_appointment_proto_init() {
	if File_proto_appointment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_appointment_proto_rawDesc), len(file_proto_appointment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_appointment_proto_goTypes,
		DependencyIndexes: file_proto_appointment_proto_depIdxs,
		MessageInfos:      file_proto_appointment_proto_msgTypes,
	}.Build()
	File_proto_appointment_proto = out.File
	file_proto_appointment_proto_goTypes = nil
	file_proto_appointment_proto_depIdxs = nil
}
